# -*- coding: utf-8 -*-
"""Model_egitim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IheekGyxBi6q4FfEOuTCe8AY7zbT3M1s
"""

!pip install scikit-learn
!pip install matplotlib
!pip install seaborn
!pip install pandas

import pandas as pd

# Dataseti yükle
df = pd.read_csv("final_dataset_5554.csv")

# İlk 5 satırı göster
df.head()

import re

def clean_text(text):
    text = str(text)
    text = text.replace("\n", " ")
    text = re.sub(r"\s+", " ", text)  # fazla boşlukları düzelt
    text = text.strip()
    return text

# Text sütununu temizle
df["text"] = df["text"].apply(clean_text)

# Çok kısa metinleri filtrele (modeli bozar)
df = df[df["text"].str.len() > 30]

print("Temizlik tamamlandı! Yeni veri boyutu:", len(df))
df.head()

from sklearn.model_selection import train_test_split

# X = metinler, y = label
X = df["text"]
y = df["label"]

# Eğitim ve test seti (80% train – 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Eğitim veri sayısı:", len(X_train))
print("Test veri sayısı:", len(X_test))

from sklearn.feature_extraction.text import TfidfVectorizer

# TF-IDF dönüştürücü
vectorizer = TfidfVectorizer(
    max_features=5000,     # en anlamlı 5000 kelime
    ngram_range=(1,2),     # 1'li ve 2'li kelime grupları
    stop_words='english'   # İngilizce stopword temizleme
)

# Eğitim ve test dönüşümleri
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

X_train_tfidf.shape, X_test_tfidf.shape

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Logistic Regression modeli
log_model = LogisticRegression(max_iter=2000)
log_model.fit(X_train_tfidf, y_train)

# Tahmin yap
log_pred = log_model.predict(X_test_tfidf)

# Sonuçlar
print("📌 Logistic Regression Accuracy:", accuracy_score(y_test, log_pred))
print("\nClassification Report:\n", classification_report(y_test, log_pred))

from sklearn.svm import LinearSVC

# SVM modeli
svm_model = LinearSVC()
svm_model.fit(X_train_tfidf, y_train)

# Tahmin
svm_pred = svm_model.predict(X_test_tfidf)

# Sonuçlar
print("📌 SVM Accuracy:", accuracy_score(y_test, svm_pred))
print("\nClassification Report:\n", classification_report(y_test, svm_pred))

from sklearn.ensemble import RandomForestClassifier

# Random Forest modeli
rf_model = RandomForestClassifier(n_estimators=200)
rf_model.fit(X_train_tfidf, y_train)

# Tahmin
rf_pred = rf_model.predict(X_test_tfidf)

# Sonuçlar
print("📌 Random Forest Accuracy:", accuracy_score(y_test, rf_pred))
print("\nClassification Report:\n", classification_report(y_test, rf_pred))

import pandas as pd

results = pd.DataFrame({
    "Model": ["Logistic Regression", "SVM", "Random Forest"],
    "Accuracy": [
        accuracy_score(y_test, log_pred),
        accuracy_score(y_test, svm_pred),
        accuracy_score(y_test, rf_pred),
    ]
})

results

import joblib

joblib.dump(rf_model, "best_model.pkl")
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

print("Model ve TF-IDF vectorizer kaydedildi!")

from google.colab import files
files.download("best_model.pkl")
files.download("tfidf_vectorizer.pkl")